// core/supabaseClient — the Supabase browser client + public config.
// Created at module load: the supabase-js CDN script and the inline
// window.SURA_CONFIG both run before app.js, so both are available here.
// The anon/publishable key is public by design — RLS does the real authorization.
export const SURA = window.SURA_CONFIG || {};

// Capture the URL hash SYNCHRONOUSLY, before createClient()'s detectSessionInUrl
// scrubs it. The password-recovery link returns the session (or an error) in this
// hash; if we read it after the SDK has consumed it, it's already gone and the
// PASSWORD_RECOVERY event can be missed by late subscribers. main.js reads this.
export const SURA_URL_HASH = (typeof window !== 'undefined' && window.location.hash) || '';

// A19 (audit, August 2026) · This called createClient() with NO options object,
// so every storage and flow decision was an invisible supabase-js default. The
// options below are deliberately mostly the defaults — the change is that they
// are now WRITTEN DOWN, because a security property nobody can see in a diff is
// a security property nobody reviews.
//
// On the token in localStorage, honestly: it stays there. sessionStorage would
// sign the player out on every tab close, which is a real regression to a real
// player in exchange for protection against an attacker who can already run
// script on this origin — and one who can do that has already won. The genuine
// mitigations for that finding are elsewhere and are now in place: the CSP,
// HSTS and frame-ancestors headers generated by scripts/build/dist.js (closing A18),
// which is what actually stands between a compromised third-party CDN response
// and this token.
//
// TWO THINGS DELIBERATELY NOT CHANGED HERE, both of which look like upgrades:
//
//   storageKey — renaming it moves the session to a new localStorage key, which
//     signs out every player who is currently signed in. A security round is
//     not allowed to spend other people's sessions.
//   flowType: 'pkce' — binds the auth code to a verifier this browser created,
//     which is genuinely stronger. It also means a recovery link opened in a
//     DIFFERENT browser than the one that requested it has no verifier and
//     fails. Sign-in is email + password (confirmation mail was cancelled), so
//     this now affects only the password-reset link — still a product decision,
//     not a security cleanup, so it is left for the owner to make.
//
// So these values ARE the current behaviour. Writing them down is the change.
export const sb = (window.supabase && SURA.SUPABASE_URL)
    ? window.supabase.createClient(SURA.SUPABASE_URL, SURA.SUPABASE_ANON_KEY, {
        auth: {
            persistSession: true,       // players stay signed in between visits
            autoRefreshToken: true,
            detectSessionInUrl: true,   // required by the recovery/OAuth redirect
        },
    })
    : null;
